# Task 5 - Sales Prediction For Existing Customer - By Harish Kumar

## Import Basic Libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = (15.0, 8.0)
from mpl_toolkits.mplot3d import Axes3D
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
import statsmodels.api as sm


## Loading The Data

In [ ]:
df = pd.read_csv("Advertising.csv")

## Extracting The Top 5 Rows

In [ ]:
df.head()

Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

# Extracting The Bottom 5 Rows

In [ ]:
df.tail()

Unnamed: 0     TV  Radio  Newspaper  Sales
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

## Summarize Dataset

In [ ]:
print(df.shape)
print(df.columns)

(200, 5)
Index(['Unnamed: 0', 'TV', 'Radio', 'Newspaper', 'Sales'], dtype='object')


## Segregate Dataset into X & Y

In [ ]:
X = df[['TV','Radio','Newspaper']].values
X

array([[230.1,  37.8,  69.2],
       [ 44.5,  39.3,  45.1],
       [ 17.2,  45.9,  69.3],
       [151.5,  41.3,  58.5],
       [180.8,  10.8,  58.4],
       [  8.7,  48.9,  75. ],
       [ 57.5,  32.8,  23.5],
       [120.2,  19.6,  11.6],
       [  8.6,   2.1,   1. ],
       [199.8,   2.6,  21.2],
       [ 66.1,   5.8,  24.2],
       [214.7,  24. ,   4. ],
       [ 23.8,  35.1,  65.9],
       [ 97.5,   7.6,   7.2],
       [204.1,  32.9,  46. ],
       [195.4,  47.7,  52.9],
       [ 67.8,  36.6, 114. ],
       [281.4,  39.6,  55.8],
       [ 69.2,  20.5,  18.3],
       [147.3,  23.9,  19.1],
       [218.4,  27.7,  53.4],
       [237.4,   5.1,  23.5],
       [ 13.2,  15.9,  49.6],
       [228.3,  16.9,  26.2],
       [ 62.3,  12.6,  18.3],
       [262.9,   3.5,  19.5],
       [142.9,  29.3,  12.6],
       [240.1,  16.7,  22.9],
       [248.8,  27.1,  22.9],
       [ 70.6,  16. ,  40.8],
       [292.9,  28.3,  43.2],
       [112.9,  17.4,  38.6],
       [ 97.2,   1.5,  30. ],
       [26

In [ ]:
Y = df['Sales'].values
Y

array([22.1, 10.4,  9.3, 18.5, 12.9,  7.2, 11.8, 13.2,  4.8, 10.6,  8.6,
       17.4,  9.2,  9.7, 19. , 22.4, 12.5, 24.4, 11.3, 14.6, 18. , 12.5,
        5.6, 15.5,  9.7, 12. , 15. , 15.9, 18.9, 10.5, 21.4, 11.9,  9.6,
       17.4,  9.5, 12.8, 25.4, 14.7, 10.1, 21.5, 16.6, 17.1, 20.7, 12.9,
        8.5, 14.9, 10.6, 23.2, 14.8,  9.7, 11.4, 10.7, 22.6, 21.2, 20.2,
       23.7,  5.5, 13.2, 23.8, 18.4,  8.1, 24.2, 15.7, 14. , 18. ,  9.3,
        9.5, 13.4, 18.9, 22.3, 18.3, 12.4,  8.8, 11. , 17. ,  8.7,  6.9,
       14.2,  5.3, 11. , 11.8, 12.3, 11.3, 13.6, 21.7, 15.2, 12. , 16. ,
       12.9, 16.7, 11.2,  7.3, 19.4, 22.2, 11.5, 16.9, 11.7, 15.5, 25.4,
       17.2, 11.7, 23.8, 14.8, 14.7, 20.7, 19.2,  7.2,  8.7,  5.3, 19.8,
       13.4, 21.8, 14.1, 15.9, 14.6, 12.6, 12.2,  9.4, 15.9,  6.6, 15.5,
        7. , 11.6, 15.2, 19.7, 10.6,  6.6,  8.8, 24.7,  9.7,  1.6, 12.7,
        5.7, 19.6, 10.8, 11.6,  9.5, 20.8,  9.6, 20.7, 10.9, 19.2, 20.1,
       10.4, 11.4, 10.3, 13.2, 25.4, 10.9, 10.1, 16

## Splitting Dataset Into Train & Test

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

# Fitting The Model

In [ ]:
regressor=LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

# Print R-Squared Values

In [ ]:
regressor.score(X_test,y_test)

0.8576396745320893

# Print Co-efficient & Intercept

In [ ]:
print(regressor.coef_)
print(regressor.intercept_)

[0.04416235 0.19900368 0.00116268]
2.89257005115115


# Finding Actual Vs predicted values

In [ ]:
y_pred = regressor.predict(X_test)

In [ ]:
df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
df1 = df.head()
df1

Actual  Predicted
0    11.3  10.049457
1     8.4   7.430523
2     8.7   6.971521
3    25.4  24.163787
4    11.7  12.002156

# Plotting The Actual Vs Predicted Values in 3D-Scatterplot

In [ ]:
fig= plt.figure(2)
ax = Axes3D(fig)
ax.scatter(X_train[:,0],X_train[:,1],y_train,color='red',label='Actual Values')
ax.scatter(X_test[:,0],X_test[:,1],y_pred,color='green',label='Predicted Values')
ax.set_xlabel('TV')
ax.set_ylabel('Radio')
ax.set_zlabel('Newspaper')
ax.set_title('Actual Values Vs Predicted Values')
ax.legend()
plt.show()

<Figure size 1500x800 with 0 Axes>

# Building Model Using Statsmodel

In [ ]:
k = sm.add_constant(X)  # addding a constant
model = sm.OLS(Y,X).fit()
predictions = model.predict(X)
print_model = model.summary()
print(print_model)

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.982
Model:                            OLS   Adj. R-squared (uncentered):              0.982
Method:                 Least Squares   F-statistic:                              3566.
Date:                Sun, 08 Oct 2023   Prob (F-statistic):                   2.43e-171
Time:                        19:53:06   Log-Likelihood:                         -423.54
No. Observations:                 200   AIC:                                      853.1
Df Residuals:                     197   BIC:                                      863.0
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

# Regularizing The Model using Ridge Regression

In [ ]:
rr = Ridge(alpha=0.01)
rr.fit(X_train, y_train)
pred_train_rr = rr.predict(X_train)
print(np.sqrt(mean_squared_error(y_train,pred_train_rr)))
print(np.sqrt(mean_absolute_error(y_train,pred_train_rr)))
print(r2_score(y_train,pred_train_rr))

pred_test_rr = rr.predict(X_test)
print(np.sqrt(mean_squared_error(y_test,pred_test_rr)))
print(np.sqrt(mean_absolute_error(y_test,pred_test_rr)))
print(r2_score(y_test,pred_test_rr))

1.5617033948198131
1.1067344635348015
0.9072183330816963
2.0031216862620074
1.1401894393460716
0.8576397111801461


# Regularization The Model Using Lasso Regression

In [ ]:
model_lasso = Lasso(alpha=0.01)
model_lasso.fit(X_train, y_train)
pred_train_lasso = model_lasso.predict(X_train)
print(np.sqrt(mean_squared_error(y_train,pred_train_lasso)))
print(np.sqrt(mean_absolute_error(y_train,pred_train_lasso)))
print(r2_score(y_train,pred_train_lasso))

pred_test_lasso = model_lasso.predict(X_test)
print(np.sqrt(mean_squared_error(y_test,pred_test_lasso)))
print(np.sqrt(mean_absolute_error(y_test,pred_test_lasso)))
print(r2_score(y_test,pred_test_lasso))

1.5617035692252104
1.106755524748352
0.9072183123586519
2.002880266832752
1.1400923820651416
0.8576740240916737


# Regularization The Model Using Elastic Net

In [ ]:
model_enet = ElasticNet(alpha=0.01)
model_enet.fit(X_train, y_train)
pred_train_enet = model_enet.predict(X_train)
print(np.sqrt(mean_squared_error(y_train,pred_train_enet)))
print(np.sqrt(mean_absolute_error(y_train,pred_train_enet)))
print(r2_score(y_train,pred_train_enet))

pred_test_enet = model_enet.predict(X_test)
print(np.sqrt(mean_squared_error(y_test,pred_test_enet)))
print(np.sqrt(mean_absolute_error(y_test,pred_test_enet)))
print(r2_score(y_test,pred_test_enet))

1.5617034519075537
1.1067460740816062
0.9072183262984673
2.0029826052887674
1.1401366820962884
0.8576594792454526
